### ISSUE TITLE
Ivy doesn't check maven-metadata-local.xml

### ISSUE THREAD

**Issue by eed3si9n** [sbt/ivy#20]
Ref sbt/sbt#1616

See https://github.com/sbt/ivy/blob/3cf31483b03e0ba294c76f5391dc7570b7649090/src/java/org/apache/ivy/plugins/resolver/IBiblioResolver.java#L166-L167

**Comment by pentaho-nbaker** [comment]
Was this not contributed back to Ivy? I still see the fixed maven-metadata.xml code in their trunk
